const ACTION_TYPES = {
  CATEGORIES: {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE'
  },
  POSTS: {
    GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',

    GET_CATEGORY_POSTS_REQUEST: 'GET_CATEGORY_POSTS_REQUEST',
    GET_CATEGORY_POSTS_SUCCESS: 'GET_CATEGORY_POSTS_SUCCESS',
    GET_CATEGORY_POSTS_FAILURE: 'GET_CATEGORY_POSTS_FAILURE',

    ADD_NEW_POST_REQUEST: 'ADD_NEW_POST_REQUEST',
    ADD_NEW_POST_SUCCESS: 'ADD_NEW_POST_SUCCESS',
    ADD_NEW_POST_FAILURE: 'ADD_NEW_POST_FAILURE',

    GET_SINGLE_POST_REQUEST: 'GET_SINGLE_POST_REQUEST',
    GET_SINGLE_POST_SUCCESS: 'GET_SINGLE_POST_SUCCESS',
    GET_SINGLE_POST_FAILURE: 'GET_SINGLE_POST_FAILURE',

    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',

    DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',

  },
  COMMENTS: {
    GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

    ADD_NEW_COMMENT_REQUEST: 'ADD_NEW_COMMENT_REQUEST',
    ADD_NEW_COMMENT_SUCCESS: 'ADD_NEW_COMMENT_SUCCESS',
    ADD_NEW_COMMENT_FAILURE: 'ADD_NEW_COMMENT_FAILURE',

    GET_SINGLE_COMMENT_REQUEST: 'GET_SINGLE_COMMENT_REQUEST',
    GET_SINGLE_COMMENT_SUCCESS: 'GET_SINGLE_COMMENT_SUCCESS',
    GET_SINGLE_COMMENT_FAILURE: 'GET_SINGLE_COMMENT_FAILURE',

    UPDATE_COMMENT_REQUEST: 'UPDATE_COMMENT_REQUEST',
    UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',
    UPDATE_COMMENT_FAILURE: 'UPDATE_COMMENT_FAILURE',

    DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',
  }
}

export default ACTION_TYPES