const ACTION_TYPES = {
  CATEGORIES: {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE'
  },
  POSTS: {
    GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',

    GET_CATEGORY_POSTS_REQUEST: 'GET_CATEGORY_POSTS_REQUEST',
    GET_CATEGORY_POSTS_SUCCESS: 'GET_CATEGORY_POSTS_SUCCESS',
    GET_CATEGORY_POSTS_FAILURE: 'GET_CATEGORY_POSTS_FAILURE',

    ADD_NEW_POST_REQUEST: 'ADD_NEW_POST_REQUEST',
    ADD_NEW_POST_SUCCESS: 'ADD_NEW_POST_SUCCESS',
    ADD_NEW_POST_FAILURE: 'ADD_NEW_POST_FAILURE',

    GET_SINGLE_POST_REQUEST: 'GET_SINGLE_POST_REQUEST',
    GET_SINGLE_POST_SUCCESS: 'GET_SINGLE_POST_SUCCESS',
    GET_SINGLE_POST_FAILURE: 'GET_SINGLE_POST_FAILURE',

    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',

  },
  COMMENTS: {
    GET_COMMENTS: 'GET_COMMENTS'
  }
}

export default ACTION_TYPES